package com.qdc_mod.qdc_core_4_5.qdc_core.boxes.particle_box.classes;

import java.util.ArrayList;
import java.util.List;

import com.qdc_mod.qdc_core_4_5.Qdc;
import com.qdc_mod.qdc_core_4_5.api.GlobalFuncs;
import com.qdc_mod.qdc_core_4_5.api.ParticleCollection;
import com.qdc_mod.qdc_core_4_5.api.QdcApi.QDC_CORE.ENUMS.TextureColor;
import com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.settings.SettingsScreenSettings;

import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

public class DefaultItemParticles {

	public List<Item> itemList = null;
	public ParticleCollection defaultParticles = null;
	public ParticleCollection configParticles = null;
	public TagKey<Item> tag = null;

	public String id = null;
	public String partialName = null;

	public ItemStack curDisplayItem = null;

	private int tickCount = 0;
	private int displayIndex = -1;
	
	public String searchString = "";

	public boolean isAutoGenerated = false;
	
	public TextureColor bgColor = SettingsScreenSettings.SEARCH_RESULT_WINDOW.ITEMS.DEFAULT_BG;
	
	
	public DefaultItemParticles(Item item, ParticleCollection particles) {

		this.itemList = new ArrayList<>();
		this.itemList.add(item);

		generateIdFromItem(item);

		if (curDisplayItem == null) {
			curDisplayItem = new ItemStack(item);
		}

		this.defaultParticles = particles.clone();
	}

	public DefaultItemParticles() {

	}

	public DefaultItemParticles setToAutoGenerated()
	{
		isAutoGenerated = true;
		
		bgColor = SettingsScreenSettings.SEARCH_RESULT_WINDOW.ITEMS.AUTO_SET_BG;
		
		return this;
	}
	
	
	public void tick() {
		if (itemList == null) {
			displayIndex = -1;
			curDisplayItem = null;
			return;
		}

		if (itemList.size() > 1) {
			if (tickCount >= Qdc.AssemblerVariables.ITEM_CHANGE_MAX_TICK_COUNT) {
				tickCount = 0;
				updateDisplayIndex();
			}

			tickCount++;
		}

		tickCount++;
	}

	private void updateDisplayIndex() {
		if (itemList == null) {
			displayIndex = -1;
			curDisplayItem = null;
			return;
		}

		if (itemList.size() == 0) {
			displayIndex = -1;
			curDisplayItem = null;
			return;
		}

		if (itemList.size() > 1) {
			displayIndex++;

			if (displayIndex >= itemList.size()) {
				displayIndex = 0;
			}
		} else {
			displayIndex = 0;
		}

		curDisplayItem = new ItemStack(itemList.get(displayIndex));

	}

	public void setConfigParticles(ParticleCollection cfgParticles) {
		configParticles = cfgParticles.clone();
	}

	public DefaultItemParticles setDefaultParticles(ParticleCollection particles) {

		this.defaultParticles = particles.clone();

		return this;
	}

	public DefaultItemParticles addTagKey(TagKey<Item> tag) {
		this.tag = tag;
		generateIdFromTagKey();
		return this;
	}

	public DefaultItemParticles addPartialName(String namePart) {

		this.partialName = namePart.toLowerCase();
		generateIdFromPartialName(namePart);

		return this;
	}

	private void appendToSearchString(Item item)
	{
		searchString += GlobalFuncs.getItemName(item);
	}
	
	public boolean addItem(Item item) {

		if (tag != null) {
			if (isValidItemForTag(item)) {

				if (itemList == null)
					itemList = new ArrayList<>();

				if (!isInItemList(item)) {
					itemList.add(item);

					appendToSearchString(item);
					
					if (curDisplayItem == null) {
						curDisplayItem = new ItemStack(item);
					}

				}

				return true;
			}
		} else if (partialName != null) {
			if (isValidItemForPartialName(item)) {

				if (itemList == null)
					itemList = new ArrayList<>();

				if (!isInItemList(item)) {
					itemList.add(item);

					appendToSearchString(item);
					
					if (curDisplayItem == null) {
						curDisplayItem = new ItemStack(item);
					}

				}

				return true;
			}
		}

		return false;
	}

	public boolean isSameID(String id) {
		if (this.id.equals(id))
			return true;

		return false;
	}

	public boolean isInItemList(Item item) {
		if (itemList == null)
			return false;

		for (Item i : itemList) {
			if (i == item)
				return true;
		}

		return false;
	}

	public boolean isValidItemForTag(Item item) {
		ItemStack tempStack = new ItemStack(item);

		if (tag != null)
			if (tempStack.is(tag)) {
				return true;
			}

		return false;
	}

	public boolean isValidItemForPartialName(Item item) {

		if (partialName != null) {
			ItemStack tempStack = new ItemStack(item);
			String tempName = tempStack.getDisplayName().getString().toLowerCase();

			if (tempName.contains(partialName)) {
				return true;
			}
		}

		return false;
	}

	private void generateIdFromItem(Item item) {
		id = GlobalFuncs.getDefaultItemID(item);
		this.searchString = id;
	}

	private void generateIdFromTagKey() {
		id = "";

		if (tag != null) {
			id += tag.toString();
			this.searchString = id;
		}

	}

	private void generateIdFromPartialName(String part) {
		id = "partial:" + part.toLowerCase();
		this.searchString = id;
	}

	public boolean isValidForSearchString(String search) {

		if (searchString == null)
			return false;

		if (searchString.toLowerCase().contains(search.toLowerCase()))
			return true;

		return false;

	}

}
