package com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.classes.settings_screen;

import java.awt.Color;
import java.awt.Point;
import java.util.List;

import com.qdc_mod.qdc_core_4_5.Qdc;
import com.qdc_mod.qdc_core_4_5.api.ParticleCollection.ParticleType;
import com.qdc_mod.qdc_core_4_5.api.GuiFunctions;
import com.qdc_mod.qdc_core_4_5.api.QdcApi;
import com.qdc_mod.qdc_core_4_5.api.QdcApi.QDC_CORE.ENUMS.TextureColor;
import com.qdc_mod.qdc_core_4_5.qdc_core.boxes.config_file_box.ConfigFileBox;
import com.qdc_mod.qdc_core_4_5.qdc_core.boxes.particle_box.classes.DefaultItemParticles;
import com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.screen.SettingsScreen;
import com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.screen.SettingsScreen.GuiButton;
import com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.settings.SettingsScreenSettings;
import com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.settings.SettingsScreenSettings.INFO_WINDOW.MSG_AREA;
import com.qdc_mod.qdc_core_4_5.qdc_core.common.gui.settings.SettingsScreenSettings.INFO_WINDOW.SETTINGS_ITEM;

import net.minecraft.client.gui.components.EditBox;
import net.minecraft.world.item.Item;

public class CfgDisplayItem {

	private final String NOT_AVAILABLE = "n/a";

	public DefaultItemParticles itemData = null;

	private SettingsScreen screen;

	public ParticleType type;
	public Item icon;
	public CfgItemPosItem posData;
	public double curVal;
	public double maxVal;
	public double minVal;
	public double defaultVal;

	public String curStr;
	public String maxStr;
	public String minStr;
	public String defaultStr;

	private List<GuiButton> btnList;

	public GuiButton btnEdit;
	public GuiButton btnSave;
	public GuiButton btnCancel;
	public GuiButton btnDefault;

	public EditBox txt;
	public EditBox txtSearch;

	public boolean isEnabled = true;
	public boolean showCurValString = true;
	public boolean isAutoSet = false;

	public TextureColor bg = SettingsScreenSettings.INFO_WINDOW.SETTINGS_ITEM.AVAILBLE;

	public String defaultMsg = "";
	public boolean isHoveringOver = false;

	public double newTxtVal = 0;

	private final Color TXT_COLOR_VALID = SETTINGS_ITEM.TXT_COLOR_VALID;
	private final Color TXT_COLOR_NOT_VALID = SETTINGS_ITEM.TXT_COLOR_NOT_VALID;

	private final Color TEXT_COLOR_ERROR = MSG_AREA.TEXT_COLOR_ERROR;
	private final Color TEXT_COLOR_SUCCESS = MSG_AREA.TEXT_COLOR_SUCCESS;
	private final Color TEXT_COLOR_DEFAULT = MSG_AREA.TEXT_COLOR_DEFAULT;

	public CfgDisplayItem(ParticleType type, CfgItemPosItem posData, DefaultItemParticles itemData,
			List<GuiButton> btnList, EditBox txt, EditBox txtSearch, SettingsScreen screen) {

		this.type = type;
		this.posData = posData;
		this.itemData = itemData;
		this.curVal = itemData.configParticles.getParticles(type);
		this.curStr = curVal + "";
		this.defaultVal = itemData.defaultParticles.getParticles(type);
		this.btnList = btnList;
		this.txt = txt;
		this.txtSearch = txtSearch;
		this.screen = screen;
		this.isAutoSet = itemData.isAutoGenerated;

		icon = QdcApi.QDC_CORE.FUNCTIONS.getParticleIconItem(type);

		setup();
		extractButtons();
		setupButtons();
		updateDefaultButton();
		setDefaultMsg();

	}

	public void onTxtChange() {
		String curStr = txt.getValue();

		if (!curStr.isEmpty()) {

			if (curStr.endsWith(".")) {
				curStr = curStr + "0";
			}

			newTxtVal = Double.parseDouble(curStr);

			handleMsgOnTxtChange();
		} else {
			handleMsgOnTxtChangeEmpty();
		}

	}

	private void handleMsgOnTxtChange() {

		if (newTxtVal < minVal) {
			setMsg("Value entered is smaller than MIN: " + minStr + " ", TEXT_COLOR_ERROR);
			btnSave.setEnabledState(false);
			txt.setTextColor(TXT_COLOR_NOT_VALID.getRGB());
		} else if (newTxtVal > maxVal) {
			setMsg("Value entered is bigger than MAX: " + maxStr + " ", TEXT_COLOR_ERROR);
			txt.setTextColor(TXT_COLOR_NOT_VALID.getRGB());
			btnSave.setEnabledState(false);
		} else {
			setMsg(defaultMsg, TEXT_COLOR_DEFAULT);
			txt.setTextColor(TXT_COLOR_VALID.getRGB());

			if (newTxtVal != curVal) {
				btnSave.setEnabledState(true);
			} else {
				btnSave.setEnabledState(false);
			}
		}
	}

	private void handleMsgOnTxtChangeEmpty() {

		setMsg("No Value Entered!!", TEXT_COLOR_ERROR);
		btnSave.setEnabledState(false);
		txt.setTextColor(TXT_COLOR_NOT_VALID.getRGB());

	}

	private void setMsg(String msg, Color color) {
		this.screen.setMsg(msg, color);
	}

	public void handleEditClick() {

		this.btnEdit.setVisibleState(false);
		this.btnEdit.setEnabledState(false);

		

		this.btnSave.setVisibleState(true);
		this.btnSave.setEnabledState(false);

		this.btnCancel.setVisibleState(true);
		this.btnCancel.setEnabledState(true);

		txtSearch.setEditable(false);
		txtSearch.setFocused(false);
		txtSearch.setVisible(true);

		showCurValString = false;

		txt.setValue(curStr);

		txt.setEditable(true);
		txt.setFocused(true);
		txt.setVisible(true);

		screen.setFocused(txt);

		updateDefaultButton();

		this.btnDefault.setEnabledState(false);
		
		screen.setMsg(defaultMsg, MSG_AREA.TEXT_COLOR_DEFAULT);

	}

	public void handleSaveClick() {
		this.curVal = newTxtVal;
		this.curStr = curVal + "";

		doSave();

		this.btnSave.setVisibleState(false);
		this.btnSave.setEnabledState(false);

		this.btnCancel.setVisibleState(false);
		this.btnCancel.setEnabledState(false);

		this.btnEdit.setVisibleState(true);
		this.btnEdit.setEnabledState(true);

		updateDefaultButton();

		txt.setEditable(false);
		txt.setFocused(false);
		txt.setVisible(false);

		txt.setValue(curStr);

		showCurValString = true;

		txtSearch.setEditable(true);
		txtSearch.setFocused(true);
		txtSearch.setVisible(true);

		screen.setFocused(txtSearch);

		screen.setMsg("Value Saved Successfully!!", MSG_AREA.TEXT_COLOR_SUCCESS);

	}

	private void doSave() {
		itemData.configParticles.setParticles(type, curVal);
		ConfigFileBox.updateCfgParticles(itemData);
	}

	public void handleCancelClick() {
		this.btnSave.setVisibleState(false);
		this.btnSave.setEnabledState(false);

		this.btnCancel.setVisibleState(false);
		this.btnCancel.setEnabledState(false);

		this.btnEdit.setVisibleState(true);
		this.btnEdit.setEnabledState(true);

		updateDefaultButton();

		txt.setEditable(false);
		txt.setFocused(false);
		txt.setVisible(false);

		txt.setValue(curStr);

		showCurValString = true;

		txtSearch.setEditable(true);
		txtSearch.setFocused(true);
		txtSearch.setVisible(true);

		screen.setFocused(txtSearch);

		screen.setMsg("", MSG_AREA.TEXT_COLOR_DEFAULT);
	}

	public void handleDefaultClick() {
		this.curVal = defaultVal;
		this.curStr = curVal + "";

		this.txt.setValue(defaultStr);

		doSave();

		updateDefaultButton();

		screen.setMsg("Value set to Default Successfully!!", MSG_AREA.TEXT_COLOR_SUCCESS);
	}

	public void updateDefaultButton() {
		if (curVal == defaultVal) {
			this.btnDefault.setEnabledState(false);
		} else {
			this.btnDefault.setEnabledState(true);
		}
	}

	private void extractButtons() {
		btnEdit = btnList.get(0);
		btnSave = btnList.get(1);
		btnCancel = btnList.get(2);
		btnDefault = btnList.get(3);

	}

	private void setupButtons() {
		if (defaultVal == 0 && !isAutoSet) {

			btnEdit.setVisibleState(true);
			btnEdit.setEnabledState(false);

			btnSave.setVisibleState(false);
			btnSave.setEnabledState(false);

			btnCancel.setVisibleState(false);
			btnCancel.setEnabledState(false);

			btnDefault.setVisibleState(true);
			btnDefault.setEnabledState(false);

		} else {

			btnEdit.setVisibleState(true);
			btnEdit.setEnabledState(true);

			btnSave.setVisibleState(false);
			btnSave.setEnabledState(false);

			btnCancel.setVisibleState(false);
			btnCancel.setEnabledState(false);

			btnDefault.setVisibleState(true);
			btnDefault.setEnabledState(true);
		}
	}

	private void setup() {
		if (defaultVal == 0 && !isAutoSet) {

			// bg color
			bg = SettingsScreenSettings.INFO_WINDOW.SETTINGS_ITEM.NOT_AVAILBLE;

			// is enabled
			isEnabled = false;

			// cur val
			curStr = NOT_AVAILABLE;

			// max
			maxStr = NOT_AVAILABLE;

			// min
			minVal = 0;
			minStr = NOT_AVAILABLE;

			// default
			defaultStr = NOT_AVAILABLE;

		} else {

			// cur val
			curStr = curVal + "";

			// max
			getMax();
			maxStr = maxVal + "";

			// min
			if (isAutoSet) {
				if (type == ParticleType.NATURE)
					minVal = Qdc.SettingsScreenVariables.MIN;
				else
					minVal = 0;
			}
			else
			{
				minVal = Qdc.SettingsScreenVariables.MIN;
			}

			minStr = minVal + "";

			// default
			defaultStr = defaultVal + "";
			txt.setValue(defaultStr);

		}
	}

	private void setDefaultMsg() {
		switch (type) {
		case NATURE:
			defaultMsg = "Editing Nature Particles";
			break;
		case FOOD:
			defaultMsg = "Editing Food Particles";
			break;
		case METAL:
			defaultMsg = "Editing Metal Particles";
			break;
		case GEM:
			defaultMsg = "Editing Gem Particles";
			break;

		default:
			defaultMsg = "";
			break;

		}
	}

	private void getMax() {
		switch (type) {
		case NATURE:
			setMax(Qdc.SettingsScreenVariables.NATURE_MAX);
			break;
		case FOOD:
			setMax(Qdc.SettingsScreenVariables.FOOD_MAX);
			break;
		case METAL:
			setMax(Qdc.SettingsScreenVariables.METAL_MAX);
			break;
		case GEM:
			setMax(Qdc.SettingsScreenVariables.GEM_MAX);
			break;

		default:
			setMax(1);
			break;

		}
	}

	private void setMax(double val) {
		maxVal = val;
		maxStr = val + "";
	}

	public boolean checkIfHoveringOver(Point windowPos, int mouseX, int mouseY) {

		isHoveringOver = GuiFunctions.isHoveringOver(windowPos, posData.iconHoverPos, new Point(20, 20),
				new Point(mouseX, mouseY));

		return isHoveringOver;

	}
}
